name: eventable
author: Daniel Robinson <daniel.robinson.dart@gmail.com>
version: 1.0.0
homepage: https://github.com/0xor1/eventable#eventable-
description: simple event system for implementing model->event->view design pattern.
documentation: https://github.com/0xor1/eventable#eventable-
dependencies:
  json_object: '>=1.0.18+2 <2.0.0'
dev_dependencies:
  unittest: any
