name: eventable
version: 4.0.2
author: Daniel Robinson <daniel.robinson.dart@gmail.com>
description: simple event system for implementing model->event->view design pattern.
homepage: https://github.com/0xor1/eventable#eventable-
documentation: https://github.com/0xor1/eventable#eventable-
dependencies:
  transmittable: '>=0.1.5 <2.0.0'
dev_dependencies:
  unittest: any
